a=input("Ho ten: ")
b=int(input("So ngay cong: "))
c=int(input("Don gia ngay cong: "))
d=float(input("He so phu cap: "))
e=int(input("Tam ung: "))
print("Nhan vien",a,end="")
f=c*b*d
print(", Co tien luong=",f,end="",sep="")
print(", Tam ung=",e,end="",sep="")
print(" va Thuc linh=",f-e,sep="")